<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Initial schema.
 */
final class Version20261001162354 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Initial schema: products, product_attributes, product_images, import_jobs';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE import_jobs (id UUID NOT NULL, status VARCHAR(20) NOT NULL, original_filename VARCHAR(255) NOT NULL, file_path VARCHAR(512) NOT NULL, total_rows INT DEFAULT 0 NOT NULL, processed_rows INT DEFAULT 0 NOT NULL, created_count INT DEFAULT 0 NOT NULL, updated_count INT DEFAULT 0 NOT NULL, failed_count INT DEFAULT 0 NOT NULL, errors JSONB NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, finished_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_import_jobs_created_at ON import_jobs (created_at)');
        $this->addSql('CREATE TABLE product_attributes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, key VARCHAR(255) NOT NULL, value TEXT NOT NULL, product_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_product_attributes_product ON product_attributes (product_id)');
        $this->addSql('CREATE TABLE product_images (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, url TEXT NOT NULL, path VARCHAR(512) DEFAULT NULL, position SMALLINT DEFAULT 0 NOT NULL, product_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_product_images_product ON product_images (product_id)');
        $this->addSql('CREATE TABLE products (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, external_code VARCHAR(255) NOT NULL, name VARCHAR(500) NOT NULL, description TEXT DEFAULT NULL, price NUMERIC(12, 2) NOT NULL, discount NUMERIC(5, 2) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B3BA5A5AE20A50B4 ON products (external_code)');
        $this->addSql('CREATE INDEX idx_products_name ON products (name)');
        $this->addSql('CREATE INDEX idx_products_price ON products (price)');
        $this->addSql('ALTER TABLE product_attributes ADD CONSTRAINT FK_A2FCC15B4584665A FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE product_images ADD CONSTRAINT FK_8263FFCE4584665A FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE product_attributes DROP CONSTRAINT FK_A2FCC15B4584665A');
        $this->addSql('ALTER TABLE product_images DROP CONSTRAINT FK_8263FFCE4584665A');
        $this->addSql('DROP TABLE import_jobs');
        $this->addSql('DROP TABLE product_attributes');
        $this->addSql('DROP TABLE product_images');
        $this->addSql('DROP TABLE products');
    }
}
